POST http://127.0.0.1:9000/instruments
Content-Type: application/json

{
  "instrumentManufacturer": "Yamaha",
  "instrumentSerialNumber": "YOB-241",
  "instrumentType": "Oboe",
  "instrumentCategory": "WOODWIND"
}

###
GET http://127.0.0.1:9000/instruments
Content-Type: application/json

###
POST http://127.0.0.1:9000/instruments
Content-Type: application/json

{
  "instrumentType": "Timpani",
  "instrumentManufacturer": "Adams",
  "instrumentSerialNumber": "29\" 2PAUFFI29D FS German",
  "instrumentCategory": "PERCUSSION"
}

