GET http://127.0.0.1:9000/members
Content-Type: application/json

###
GET http://127.0.0.1:9000/members/6

###
POST http://127.0.0.1:9000/members
Content-Type: application/json

{
  "firstName": "Jonas",
  "lastName": "Miu",
  "memberStatus": "ACTIVE"
}

