GET http://127.0.0.1:9000/members
Content-Type: application/json

###
POST http://127.0.0.1:9000/members
Content-Type: application/json

{
  "id": 4,
  "firstName": "Mia",
  "lastName": "Miu",
  "memberStatus": "ACTIVE"
}
